---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-keys
  namespace: crowdsec
spec:
  encryptedData:
    BOUNCER_KEY_FIREWALL: AgBAoduYqGFibqklIw9Fa05J8TfLyYc2ErEdUrFbzb0YZqv4c16mMV+f2M7r+HLx0CUb9d+EDM6TkLg7Uq9pD0o9+FDB8WyANYHswbQ50Am4l7OXP/2xs35OflXkrAD6tBPfSPEsKesVR7zynh1tMndF9kH+TAtblgwgUUdcj9LAGIvQ243Z8OftsYMh0t8pgjrF9lHblXU/AuPTxu5gwfBrvTVtGaXT67hmN4sDcd9uTQHF6aDMNNcs1j2/eB0BoK3dqM1/0g1FwkyQtzc7SSTc42DyIIGvFA3kM95iIF45mW3IVLF/zIiXE810QOCrpSmHhL0MvNhlvXtvZfC0UtmQK0N7T8F5HbYQ44kFnkFkitjchCAPRUNUn7SYwhPovIRbOV4tXYJsf79UkFKTrFCmlNralK+EA3JuDtv1SZQqVqyxkWaqOHbBDVXGeE/9IP91ow5cEBVC6DKb5VNC5m9EHVkIrbiT70MtNExDJJK8ZazgEJSA+KyG/PpFjFH7aP44n6ECK5tc3aYkUJqdI/+qDkme9SAYZEXW2mF99Y+/++gvMS6mRgqlukSaVSliJ7NN4Z82y7rlYZD9YRTESWUYUIfEK70zIjwbtj8PM47jkT0kVj9JD5zB5txJOSzHsswi4C7aANeRVoSMI8X2yFnCilZ8WFbMBI8qilGynxNSjZQSZuLc59Wdx1lTuk1ZCsqYkFnOX1QMLQneqmsXS7d47URoBQASCzrmq+QojU6GW1l4OGfdxL0ASUiQs5Ocvb+CQyXXvt7KittRLr9mtWP8
    BOUNCER_KEY_TRAEFIK: AgAaQHjWURtWK8M5fIYE7wJM4unqXIsPdvhmiZi1kKfdtzu29U4LMX+XTi5plG7EhsGjWH/b11dKDKnyDlWZw46NRsMmtNAvdaEckeJRNs9NFM93pZlVtw/sY21IXecM6hvmEKuwikw7RB+LQweJA6GR4MgaShlJLTFU4W46Q0WFMBKdfqgEp3ejJbHsU1m4RGlHl0AULNy6YM6C+ZvE/nL1o1p0QUv7J7zDS2e95N2L5oxPA+rKQyBxqx04rGqmlZvTSGlSuRq1yKnrF5xEYW6OPvyutwNwzKU1AHGe5lB0TVPPkDX8aLRhrwp4dML0fOdWiq1nfwrrgVoafu1FJLnL8f1NvQHT8EBfd0/g/nNduOaD6QuOw6WdXI/30Vslp+qkhBgZiqUR8vnx+rKQlZYtump+9dLjRA48X9h7iPbuBpOvdILxkzik+Jo0H+8vdgP+GHBwouQa7o2vmpUaoMaqfYSTAttttcLjBieeP/GjGa5b0sSJT/5cH9XjSAZ1Lc2580W+m95UuuE4v+SXKwqoS4MV2IqGQ/jJJPuXMPOsF4AatuRWN5J399EjuHcFn6KhYun7MLFby/7Fud3nqZS45FXRtc7wrkzADuHxneyysLYS+Wpwqav/ET5nzWUXBQpzN8HkIERl/XQnJqrerMWA8sUqlUyUta61oA3i8EnLjHWYdtVdAwOvDmYnwSnyQRLUlaJ2UxAHb1HbqxRvoMC5Z4kNZzgv4cjBxWJcdU8iYrXPitHxfTHl80PwegnwKlAWUv1ZO9E+iFOdDqefXimn
  template:
    metadata:
      name: crowdsec-keys
      namespace: crowdsec
    type: Opaque
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-bouncer-key
  namespace: kube-system
spec:
  encryptedData:
    BOUNCER_KEY_traefik: AgBmntywuss+HxfbxabA4jTD9aony7/rYDfQhkIPKyrPT/rIXxLwbjWWdfE05dwj9TxkhMQ5r+VgTxqZKWEj26yHG/Woox3SK4nDshWvktBkNionPUo3uTpvLFmR1uXknbwOGI2nadPXmvpdUvOv9SnLs8d3P6aRVXh7qFqdIX1kAwW7ptJW5TWLKo2aQZUkpa9LEC1hsnb+SOCXSTuJmmt76Hsf7kZpKHnn8dGhCWJL4UptDcHl+EDVkbUV1M6KPo7l8kwDoL5q25rK6VBYSue52un6+pNDNNRluxP32VlYa5pXI9ABByelSsEb6gawh61X23Nh9NbyymJEKK6ZYCutoL20cCtq3S6VpJgLmMnED0svg1OnQZOGEsLlaYPr4yxkyX0FZRFtlutpFGVJPX3t6Oz+iStujJAxWp+gCp6NtieNNZ4zJC8QW2a5S6bl0t4YY8Sayar3Ugw/xkEq8NMBLBMmQ62Ak+2nrFBlW0Vzo8Az6oynf30BEnCzsq4YEHhc3qOTK2UBgf7pnNH3gW6zxoVK2cUBwBs9QIBZo+PtNTMbUEfev0SHeg24xtxOfcHqt14iJOfcHcfgBq1oZovxZCbD+2UdwtolFVHVjl8BIfPVDqcv0BPbT8GIyt/yeda0whZpp/EifYcVfql9paF238XJE1kOX4HFnL890EIc9KRY0sn30AAAU2Q5YQRFOMs0IaD+WRMa2g3rzc/WjNrv7WbzBuc45nhtaiAwiBpSvbWw1DP5QatM1uctXW2lZO1YhPwI6o7l9ekiSmQxW7NG
  template:
    metadata:
      name: crowdsec-bouncer-key
      namespace: kube-system
    type: Opaque
