---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oauth2-proxy-credentials
  namespace: oauth2-proxy
spec:
  encryptedData:
    client-secret: AgA1tV1r0GcJKR+Z3oX9qp6nGNITillSZ4H9e9Wt110ci12oFqqoVMK7+WhGILPjbb+J3+iIGo5C9+vU+xcWXi1fbk6Xe1EbW9fV1z47lG+el/4nQOOoUAjkIs107FEiN9O1ZYL+UrUWdALWm8jw/CYka6WjNj+TEFsp7K7eKc6UDCjvYKuIj7eypft3i+Ejh1oKA4tgtlZ0bZLsd0SIPqak9tVbyX6n8DxRIKrvfa0VfDhu/p/+8dlgWg/t4hIQYB8qmQu/XMI59x0a2DWbLokM20O3B1Nect2PDsAAbQwS+eGsu2mQsTY8CbxdJ1v982HKpZRBreNjryH9Zto1OeFOJwipbX8c+SBwylx9/ZWwrawAmKix6pEyccVcnDM/SnwXkAkvj6ILERkrlKKPjnxtHbzzRcPLXcm23m8jjh8t1GGVIxOapBdDfImlV8uNAs95jzWPgYovrhEum/PzdREcL2qB31p+dBr2TDmCw/eerVUa08HQNZxhWLjygWAij3L+I8zqxioE7h7CvtT8yZBIOIgSbnwz/OMS9kxUzPcJAyc/pMuKyG7qcOOb+Zi5NLFP+hujxZ56THr5Vn66aD1EijFp4Yem1pr16HwQ207W+6n5ZH2QqqgnZkvVzZ2p4RcaLY2xgBcYF5r+JACianWu8LjoOih5WVJohg1kMwkWjwJKWxVWCvyhZEy+6H0bdwhEyKVPZzEhP5DQMmmoq+sCAKgipvHpEWeIPGf7/vj2gvkuCsztdRBL
    cookie-secret: AgAkl/f2thCFTp9/uery02rXmdr3a+ph6N9GGvQ6q3jLK6NyVtn8X0v0kXoatbW9mJQiHcglvNAaSvOPRHDbzwscTu5UZEwylUyU3820AA1TV2oH3VIO8daoL1tzQZb6/dg1RYUfayEJsNytfyYRVhB6KHfFacgvvZaiEWrtE0FgzgZu6J9yRy7jjR+Umw1AOY/8xTbhibo/OcdfajqWVS2Zv/jhq9mUAvoSWq6zQlP4LNKOCSke3yW/8O2oYqOGMUyX+yBn8uMPw1AlKINDOlXyWB/SBNdUFx2sp96ahlzMGUYnZRgSTmjIYUYRBo3a/MgvCXHz9VWVwAUxPybE/BS6xpZB8koyIbAR0gcB2wr+yWuDvi+9NST7zSKaQNUhKbGKOP+4nnXBzixpabTbNL2yoUF9fu/gwAgtLeLRb8ISZLyAvx8Z9vb7bdcfKu6kKr+Zl4T17Ar5sy5dlnIZwv/HuUCXBlZtSnGk/MqcOPmvv4EdZ2uu8xBVtkk1KiNfYqqlNyPe+q8/cM9oLgIwd87MxlCu/xaNGkK1Lu7wP9My3Afl+DX0t4cwrAYRQaCP8nVatxSnwBhXLanV1LT8eKzyGkCKIQK8JzrmF92qFMG5uN0krazJ+Yyt4fQHcw7rK1rqTOMwKqNyO+4xa0TiNJV/FCUTPw4bxPhD9fiygXuKS0b7d4RI181QZx2tiMEkFzl457A1iwTOZiATE0EHzWfIMQJTbPEgyY9se9Od24gygg==
  template:
    metadata:
      name: oauth2-proxy-credentials
      namespace: oauth2-proxy
    type: Opaque
