---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oauth2-proxy-credentials
  namespace: oauth2-proxy
spec:
  encryptedData:
    client-secret: AgCfIowc5wqy8L5xA6ywIQinXj8ANkjT9XlMmGWJ0deH7AxCahz6SA/rxbeNXpBb/GC8OxaJAFP0pMlryF3dmQA44XOzgtIk6gF2yAlNcPH6Ra29mwdI6mgZ5xW28Z3RkC0uVp0Adw994HgWPJbstl45m51oXnD45U4NIHAQyrZly5SewPJkvfLMM8R/zHFJsdwIKBZJa/cDYEayLCEzYcl7eTwN6IaZL8IeIKZ/ORUAs0JerTOP4x3OekLVaHJqztZyuMBHxeoJbvJIWNGJ4KoQP7ZvrTlwGLKLhDMfg0361mbIMuAHZF/agx8TYTXv8qRzKpgFaAbfr4DIH6/96dcw0MxukvhGr4o1DlCQTKoo7XEiC9DF32VAnD/45f4AXSezA7JfWShLTtKmM1QnkSipf0JZ2Ki+lkWeHZMNomkS0aNKSYQHshDpSBTj5DYUYLS2EG+I8EeUc+HXhu1flxpce+5r2hCmsSjMtE4GWUJeNP/uOXwjihocmGb19hxiErrOaU4GMWpJKcyZ3HqS0tI5bK/VU6yVBHk6FEtkF2rxGLuc7U0IAenU4b1YKKtLn66PSmq3A0a8on+29OZJYy2npWpQjqkafk9gZLfOBAzbG16MtiCGhBVJ+xGGvn3Z/wqaOsy9XurDdVIK39xeXh/43aRxwIZoxfCFq+SVOavEEdsiomFuRhsH+4J/JlhspsDuCIPOUcecQHxWqxyezHztIc/2yZ0ewIhyBrbZlZDlx7BEYxENporf
    cookie-secret: AgBHQb9Ez+8bz/akXYSD9ssNgKRYDNFkcc0NtKUXIVRE35tf9xfTnhffIID0TXK3L8nmpcOgmGvITuMsjFoj7XFKGXGbzyOGXvtOgsrYz+8nUofwmFsVA5AnzB1z4eW7lmZb0z3E+xkoRUYT/ydF4VstOQLYCZc53NOkdu4TjeQixSxIIKJ60/TbqeKeanrcw5TnxDf+sQno71+r0WLNG4UtTzIn1q8f3ZRhKa+s4vaVg7rUOOw1IpyQa0FXsAS2fRuNknUCmkRGcF6e20deUaaeGBup5vFHSCMLoQU8yTxL/gzjvNK2vPnPBD7LAEJiTusnShf81syj9HFDHrm3926S1RFvHt4sSE/GL9w3atR0xA9yjfctPW4LV31HyijSc8RxoVMI8pHOePxpQu83AUopk8xpSGy9HL/nWnfeVI9NdFgBUcKtLOGwzDHxOG3OLOYy4rh8ZTg1ggBPHsSa/YM4JeLfn66ZI2VALJa7ST47HaFzB2fcNcjVCqikn/Bn4Nq2rNp6C5diUdRvsV5zJFZhSETSb56ZqkAURDN9nMocnc22YtURnebfZhKl+P6v/ffenUGkNeTI7V+wiEyl7NEatSLtJN1i3W/7U3m4nCRKNT78RjpIH+yMbSBvD7TPsSPlJO4IRA8K9LT0bODrPWvFtZDeEBB/un7LQ833WCsvok7K2XI2as2/BrRjtJ9naC2SpH9mEhKtRBNHdPtJ5cxPP62bs8qHdKfGG9SRj2AinA==
  template:
    metadata:
      name: oauth2-proxy-credentials
      namespace: oauth2-proxy
    type: Opaque
