
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crowdsec-stack-crowdsec-extras
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Itoash/homelab-k3s.git # homelab-repo
    targetRevision: HEAD
    path: crowdsec-stack/base/crowdsec-extras
  destination:
    server: https://kubernetes.default.svc
    namespace: crowdsec
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true